// Builds the source archive AMO requires when submitted code is machine-generated.
//
// Contains everything needed to reproduce packages/ext's firefox-mv2 build, and nothing
// else. packages/protocol is included deliberately: ext inlines it at bundle time, so a
// reviewer given only ext cannot reproduce the output.
//
//   node build-source.mjs   (or: pnpm --filter ext source)

import { execFileSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
// Stage outside the repo: keeps the working tree clean and avoids copying into a
// directory the build is simultaneously reading from.
const stage = mkdtempSync(join(tmpdir(), 'portage-source-'));
const outDir = join(here, 'web-ext-artifacts');

// There is no static manifest.json anymore — WXT generates it at build time. Build
// first so there's a real one to read version/id back out of.
execFileSync('pnpm', ['run', 'build:firefox'], { cwd: here, stdio: 'inherit' });
const manifest = JSON.parse(readFileSync(join(here, '.output/firefox-mv2/manifest.json'), 'utf8'));
const rootPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const version = manifest.version;
// "pnpm@12.3.4+sha512.961aa..." -> "12.3.4"
const pnpmVersion = String(rootPkg.packageManager ?? 'pnpm@unknown')
  .split('@')
  .pop()
  .split('+')[0];
const nodeRange = rootPkg.engines?.node ?? '>=22';

const rootFiles = ['package.json', 'pnpm-workspace.yaml', 'pnpm-lock.yaml', 'tsconfig.base.json'];

// Per-package: the listed directories are always copied wholesale, plus the listed
// files if present.
const packages = {
  protocol: { dirs: ['src'], files: ['package.json', 'tsconfig.json', 'vitest.config.ts'] },
  ext: { dirs: ['entrypoints', 'lib'], files: ['package.json', 'tsconfig.json', 'wxt.config.ts'] },
};

mkdirSync(outDir, { recursive: true });

for (const file of rootFiles) {
  const from = join(root, file);
  if (!existsSync(from)) throw new Error(`missing required root file: ${file}`);
  cpSync(from, join(stage, file));
}

for (const [pkg, { dirs, files }] of Object.entries(packages)) {
  const from = join(root, 'packages', pkg);
  const to = join(stage, 'packages', pkg);
  mkdirSync(to, { recursive: true });
  for (const dir of dirs) {
    cpSync(join(from, dir), join(to, dir), { recursive: true });
  }
  for (const file of files) {
    const src = join(from, file);
    if (existsSync(src)) cpSync(src, join(to, file));
  }
}

writeFileSync(join(stage, 'BUILD.md'), buildDoc());

const out = join(outDir, `portage-source-${version}.zip`);
rmSync(out, { force: true });
execFileSync('zip', ['-qr', out, '.', '-x', '*.DS_Store'], { cwd: stage });
rmSync(stage, { recursive: true, force: true });

console.log(`source archive: ${out}`);

function buildDoc() {
  return `# Portage (Zen) — source and build instructions

Submitted add-on: **${manifest.name} ${version}**, id \`${manifest.browser_specific_settings.gecko.id}\`

This archive contains the complete source for the submitted add-on. The project is a pnpm
workspace; \`packages/ext\` inlines \`packages/protocol\` at bundle time, so both are
included. Other workspace packages are not part of this add-on and are omitted.

## Environment

- Node.js ${nodeRange} (built and verified with ${process.versions.node})
- pnpm ${pnpmVersion} — pinned in the root \`packageManager\` field; \`corepack enable\` selects it

## Build

    corepack enable
    pnpm install --frozen-lockfile
    pnpm --filter ext build:firefox

## Output

\`packages/ext/.output/firefox-mv2/\` will contain exactly the files in the submitted
package:

| File | Origin |
|------|--------|
| \`manifest.json\` | generated by WXT from \`packages/ext/wxt.config.ts\` and \`package.json\` |
| \`popup.html\` | generated from \`entrypoints/popup/index.html\` |
| \`background.js\` | Vite/Rollup bundle of \`entrypoints/background.ts\` |
| \`chunks/popup-*.js\` | Vite/Rollup bundle of \`entrypoints/popup/\` (React) |

The build tool is [WXT](https://wxt.dev), configured in \`packages/ext/wxt.config.ts\`.
Minification is explicitly disabled (\`vite.build.minify: false\`), so the emitted
JavaScript is readable and maps directly onto the TypeScript sources.

Signing (\`pnpm --filter ext sign\`) rebuilds via \`wxt build -b firefox\` and then runs
\`web-ext sign --channel unlisted\` directly against \`.output/firefox-mv2/\`, producing the
signed \`.xpi\` under \`web-ext-artifacts/\`.

## Notes for review

- No third-party services. The extension opens a WebSocket only to a URL the user types into
  its own popup, stored in \`browser.storage.local\`.
- No analytics, no telemetry, no remote code execution, no \`eval\`.
- Received URLs are stored, never navigated to automatically. The user must click "Open" in
  the popup, and only \`http:\` and \`https:\` schemes are accepted.
`;
}
